name: Windows Virtual Machine

on:
  workflow_dispatch:

jobs:
  windows:
    runs-on: windows-latest

    steps:
      - name: Testar Windows
        shell: pwsh
        run: |
          Write-Host "Windows runner funcionando!"
          systeminfo
          Write-Host ""
          Write-Host "Usuario:"
          whoami
